### ISSUE TITLE
Can't run iosApp

### ISSUE THREAD

**Issue by alfianyusufabdullah** [kotlin-hands-on/kmm-networking-and-data-storage#1]
Hi, I'm trying to run this project in android studio. But getting this error:

`Error: Please check specified Xcode project file: can't grab Xcode schemes with /usr/bin/xcodebuild -project /Users/alfianyabdullah/Downloads/kmm-networking-and-data-storage-master/./iosApp/iosApp.xcodeproj -list`

what should I do to fix that?

**Comment by LenaDev** [comment]
Hi @alfianyusufabdullah 
How did you solve this issue?

**Comment by alfianyusufabdullah** [comment]
@LenaDev  install Cocoapods and done.
