### ISSUE TITLE
iOS example not working correctly, throws: mutation attempt of frozen kotlin.collections.HashMap

### ISSUE THREAD

**Issue by falcon4ever** [kotlin-hands-on/kmm-networking-and-data-storage#12]
Hi,

I was following the tutorial [Kotlin Multiplatform Hands-on: Networking and Data Storage](https://play.kotlinlang.org/hands-on/Networking%20and%20Data%20Storage%20with%20Kotlin%20Multiplatfrom%20Mobile/01_Introduction) from scratch using **Android Studio Arctic Fox Beta 4** and **KMM plugin v0.2.6**.

The Android demo works great, the iOS demo seems to have a problem trying to retrieve the data from the shared KMM module.

I also noticed that the iOS template that's generated with KMM plugin v0.2.6 is different from the one in the tutorial and this repo. The plugin now generates a template with iOSApp.swift and ContentView.swift only (there is no AppDelegate.swift or SceneDelegate). In my fork I made some changes to make it run, unfortunately, it gives me the following error when launching: "mutation attempt of frozen kotlin.collections.HashMap@1cad628"

<img width="1505" alt="Screen Shot 2021-06-29 at 5 07 08 PM" src="https://user-images.githubusercontent.com/480019/123868090-3a37e800-d8fd-11eb-9d2d-b312b79d340d.png">

Steps to replicate:
- Clone my fork: https://github.com/falcon4ever/kmm-networking-and-data-storage/tree/final-AndroidStudio_ArcticFoxBeta4-KMM_v0.2.6
- in the **iosApp** folder, run **pod install** / **pod update** before opening the xcode project (or building/running the iOS project from Android Studio)

Any ideas how to fix the demo code?

I'm using:
-  Kotlin: 1.5.20
- Coroutines: 1.5.0-native-mt
- Serialization: 1.2.1
- ktor: 1.6.0
- sqldelight: 1.5.0

*edit June 30th 2021*
I also tried updated the existing **final** branch to see if it was some XCode proj issue (but it gives the same result): 
- https://github.com/falcon4ever/kmm-networking-and-data-storage/tree/final-patched-AndroidStudio_ArcticFoxBeta4 
- https://github.com/falcon4ever/kmm-networking-and-data-storage/commit/10f4644a4d66a7f97819b784dfe3a15dcd4b0247

**Comment by falcon4ever** [comment]
Ok, figured it out and it's related to the serialization library:
- https://twitter.com/joreilly/status/1412701348638900227
- https://github.com/Kotlin/kotlinx.serialization/issues/1450

If you add `useAlternativeNames = false` in `SpaceXApi.kt` the iOS app will work correctly:
```
class SpaceXApi {
    private val httpClient = HttpClient {
        install(JsonFeature) {
            val json = Json {
                ignoreUnknownKeys = true
                useAlternativeNames = false
            }
            serializer = KotlinxSerializer(json)
        }
    }
```

**Comment by KaterinaPetrova** [comment]
Hey @falcon4ever, thanks for reporting it. I've updated the sample (added a workaround). The final branch was forced-pushed (to keep the clean history, which represents the steps of the tutorial)
