### ISSUE TITLE
Project not compatible with latest Android Studio version (Bumblebee 2021.1.1)

### ISSUE THREAD

**Issue by morale3232** [kotlin-hands-on/kmm-networking-and-data-storage#13]
Upon cloning this project and opening in Android Studio, version Bumblebee 2021.1.1, an error is thrown during gradle sync. The error looks like this:
<img width="497" alt="Screen Shot 2022-02-02 at 11 42 06 AM" src="https://user-images.githubusercontent.com/15097169/152207987-102d383e-390e-4b9d-adfe-4e45b5d98277.png">
"

When I select "Cancel (and update build files manually), I get the error `The project is using an incompatible version (7.0.0-beta05) of the Android Gradle plugin.
Upgrade to the latest version` 

When I select "Begin Upgrade" and then "Upgrade", it tries to build and then gives the error "Please initialize at least one Kotlin target in 'shared (:shared)'."

**Comment by pahill** [comment]
Thanks for taking the time to fill this issue. I doubt this is still an issue as we're now on Jellyfish.
