### ISSUE TITLE
Question about Coroutine dependency

### ISSUE THREAD

**Issue by ArcherEmiya05** [kotlin-hands-on/kmm-networking-and-data-storage#16]
Good day, I just wanted to ask why we use `org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.0-native-mt` instead of the regular `org.jetbrains.kotlinx:kotlinx-coroutines-android:$version` here. Is there any specific reason or is it mandatory when working with KMM?

Thanks

**Comment by ArcherEmiya05** [comment]
> Hi! Quoting John's reply from [this StackOverflow question](https://stackoverflow.com/questions/67856900/whats-the-different-between-native-mt-and-normal-kotlin-coroutine-lib):
> 
> > It basically provides capability to use multiple threads in Kotlin/Native code (typically as part of a Kotlin Multiplatform (KMP) project). Some more info at https://kotlinlang.org/docs/mobile/concurrency-and-coroutines.html#multithreaded-coroutines. This is also version used now by many KMP libraries (e.g. Ktor) and is generally a requirement when developing KMP apps.

Thanks a lot

**Comment by SebastianAigner** [comment]
According to [this comment](https://github.com/Kotlin/kotlinx.coroutines/issues/462#issuecomment-999557659), it's no longer required with the new Memory Model for Kotlin/Native, so yes, the replacement would be the regular version.
