### ISSUE TITLE
AndroidApp: Blank screen on data load success

### ISSUE THREAD

**Issue by shettychirag7** [kotlin-hands-on/kmm-networking-and-data-storage#2]
Hi team,

Firstly, thank you for the wonderful demo. It has been really helpful in understanding the configuration. Just like to highlight a slight issue in activity_main.xml below which is causing a blank screen when data fetch is successful.

`<androidx.swiperefreshlayout.widget.SwipeRefreshLayout
      android:id="@+id/swipeContainer"
      **android:layout_width="0dp"
      android:layout_height="0dp"**
      app:layout_constraintBottom_toBottomOf="parent"
      app:layout_constraintEnd_toEndOf="parent"
      app:layout_constraintStart_toStartOf="parent"
      app:layout_constraintTop_toTopOf="parent">`

Setting the above from 0dp to match_parent should solve the issue.

**Comment by KaterinaPetrova** [comment]
I've fixed the issue as you suggested here https://github.com/kotlin-hands-on/kmm-networking-and-data-storage/commit/2f0abc1e4a8716b9d7d3abd3b443e01951b03046, thanks a lot for reporting and for the kind words! ❤️
