### ISSUE TITLE
Branch "outdated"

### ISSUE THREAD

**Issue by Sartoric** [kotlin-hands-on/kmm-networking-and-data-storage#22]
I've noticed that the "final" branch is not using the same dependencies versions used in the tutorial 

eg. 
||branch|tutorial|
|-|-|-|
|Sql Delight|1.4.2 (gradle properties)|1.5.3|
|plugin.serialization|1.6.21|1.7.21|

and some other discrepancies
eg. AppDatabase.sq

**Comment by pahill** [comment]
This should be fixed now. Thanks for taking the time to file this request. We've recently updated the whole thing.
