### ISSUE TITLE
Unresolved reference: com.squareup.sqldelight.drivers.native.NativeSqliteDriver

### ISSUE THREAD

**Issue by danailalexiev** [kotlin-hands-on/kmm-networking-and-data-storage#4]
Hi, 

KMM looks awesome.  KUDOS to you guys for making it happen.

I tried following the official Hands On exercise, but I quickly ran into a problem. Android Studio can't resolve the reference to com.squareup.sqldelight.drivers.native.NativeSqliteDriver.

I tried importing the final version of this project, but I got the same problem again.

This is my build file:
```
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

plugins {
    kotlin("multiplatform")
    id("com.android.library")
    id("kotlin-android-extensions")
    kotlin("plugin.serialization")
    id("com.squareup.sqldelight")
}
group = "bg.dalexiev.kmmexample"
version = "1.0-SNAPSHOT"

val coroutinesVersion = "1.3.9-native-mt"
val serializationVersion = "1.0.0-RC"
val ktorVersion = "1.4.0"
val sqlDelightVersion: String by project

repositories {
    gradlePluginPortal()
    google()
    jcenter()
    mavenCentral()
}

kotlin {
    android()
    ios() {
        binaries {
            framework {
                baseName = "shared"
            }
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")

                implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:$serializationVersion")

                implementation("io.ktor:ktor-client-core:$ktorVersion")
                implementation("io.ktor:ktor-client-serialization:$ktorVersion")

                implementation("com.squareup.sqldelight:runtime:$sqlDelightVersion")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
        val androidMain by getting {
            dependencies {
                implementation("com.google.android.material:material:1.2.1")

                implementation("io.ktor:ktor-client-android:$ktorVersion")

                implementation("com.squareup.sqldelight:android-driver:$sqlDelightVersion")
            }
        }
        val androidTest by getting {
            dependencies {
                implementation(kotlin("test-junit"))
                implementation("junit:junit:4.12")
            }
        }
        val iosMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-ios:$ktorVersion")

                implementation("com.squareup.sqldelight:native-driver:$sqlDelightVersion")
            }
        }
        val iosTest by getting
    }
}

android {
    compileSdkVersion(29)
    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    defaultConfig {
        minSdkVersion(24)
        targetSdkVersion(29)
        versionCode = 1
        versionName = "1.0"
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
}

sqldelight {
    database("AppDatabase") {
        packageName = "bg.dalexiev.kmmexample.shared.data.local"
    }
}

val packForXcode by tasks.creating(Sync::class) {
    group = "build"
    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val sdkName = System.getenv("SDK_NAME") ?: "iphonesimulator"
    val targetName = "ios" + if (sdkName.startsWith("iphoneos")) "Arm64" else "X64"
    val framework = kotlin.targets.getByName<KotlinNativeTarget>(targetName).binaries.getFramework(mode)
    inputs.property("mode", mode)
    dependsOn(framework.linkTask)
    val targetDir = File(buildDir, "xcode-frameworks")
    from({ framework.outputDirectory })
    into(targetDir)
}
tasks.getByName("build").dependsOn(packForXcode)
```

I tried to define separate iOS targets for the simulator and actual device, as proposed in [this](https://stackoverflow.com/questions/62916210/unresolved-reference-nativesqlitedriver-for-sqldelight-added-to-ios-source-se]) stackoverflow thread, but then gradle couldn't fine the iOSX64 target.

I tried on Android Studio 4.0.1, Android Studio 4.1.0-RC3 and IntelliJ IDEA.

Do you have any idea how to fix this or work around it?

**Comment by hlnstepanova** [comment]
adding this to the shared build.gradle helped me

val onPhone = System.getenv("SDK_NAME")?.startsWith("iphoneos") ?: false
     if (onPhone) {
         iosArm64("ios")
     } else {
         iosX64("ios")
     }

**Comment by rhonyabdullah** [comment]
> adding this to the shared build.gradle helped me
> 
> val onPhone = System.getenv("SDK_NAME")?.startsWith("iphoneos") ?: false
> if (onPhone) {
> iosArm64("ios")
> } else {
> iosX64("ios")
> }

Adding this will solve the problem but it leading to another error that causes [Serializable](https://github.com/kotlin-hands-on/kmm-networking-and-data-storage/blob/1f67a228290d58d31eb743ad649712adcf82352e/shared/src/commonMain/kotlin/com/jetbrains/handson/kmm/shared/entity/Entity.kt#L6) annotation is missing.

**Comment by iRYO400** [comment]
@hlnstepanova didn't helped, just throws `Unresolved reference: iosArm64`

So the issue is still relevant

**Comment by KaterinaPetrova** [comment]
Hey! Thanks for reporting the issue. This KMM project uses the new Kotlin Multiplatform Feature — [hierarchical project structure](https://blog.jetbrains.com/kotlin/2020/06/kotlin-1-4-m2-released/#hierarchical-project-structure). But as mentioned [here](https://kotlinlang.org/docs/reference/migrating-multiplatform-project-to-14.html#migrate-to-the-hierarchical-project-structure):

> libraries published without the hierarchical project structure can’t be used in a shared native source set. 

SQLDelight hasn't migrated to hierarchical project structure yet, that's why Android Studio can't resolve the reference to `com.squareup.sqldelight.drivers.native.NativeSqliteDriver`. Actually, this is the problem only with the IDE support and you are still able to compile and run this code, even with these import errors. But of course, this is unexpected behavior. So I fallbacked to the "hack" with switching targets for now. And we will update [our documentation](https://kotlinlang.org/docs/mobile/home.html) soon and give an explanation and list of "legal" temporary workarounds for this.

https://github.com/kotlin-hands-on/kmm-networking-and-data-storage/blob/master/shared/build.gradle.kts#L19
