### ISSUE TITLE
Blank screen on real iOS device

### ISSUE THREAD

**Issue by ln-12** [kotlin-hands-on/kmm-networking-and-data-storage#6]
I cloned the final branch of this project. When running it in the simulator, everything seems to work as expected and I can see the UI. Running on a real device (iPad mini 4, iOS 13.3), the screen is just blank after app startup. No errors are shown. Am I missing some configuration?

When replacing the body block like the following inside `ContentView.swift`, I can see the text.

```
var body: some View {
        /*NavigationView {
            listView()
            .navigationBarTitle("SpaceX Launches")
            .navigationBarItems(trailing:
                Button("Reload") {
                    self.viewModel.loadLaunches(forceReload: true)
            })
        }*/
        Text("Some content")
    }
```

**Comment by KaterinaPetrova** [comment]
Hey @ln-12! I wasn't able to reproduce this issue on my device. I've updated the project, could you please check if the issue still exists?

**Comment by ln-12** [comment]
@KaterinaPetrova Hey, thanks for the response. I tried it again with a device running a preview of iOS 15 and now it's working. Maybe the issue was related to iOS 13 as I also had some other problems with it.
