### ISSUE TITLE
Tutorial Out of Date

### ISSUE THREAD

**Issue by trevorholliday** [kotlin-hands-on/kmm-networking-and-data-storage#8]
In the tutorial for this project during step 3 you inform us to add `sqlDelightVersion=1.4.1`.

Version 1.4.1 has a bug that only marks the generated SQL files as iOS. 

In your project you are using 1.4.2 to get around this issue.

Please update the tutorial.

**Comment by KaterinaPetrova** [comment]
Thanks for reporting the issue! I've updated tutorial here: https://github.com/kotlin-hands-on/hands-on/commit/2e9ce89deb90bc4bbca46d7e6de103140ee031f5
